### ISSUE TITLE
Recover LPhyBEAST after new structure of data and model

### ISSUE THREAD

**Issue by walterxie** [alexeid/linguaPhylo#68]
data {
  D = nexus(file="examples/primate.nex", charsets=["noncoding", "coding"]);
  coding = partition(alignment=D, name="coding");
  noncoding = partition(alignment=D, name="noncoding");
  L1 = nchar(coding);
  L2 = nchar(noncoding);
  taxa = taxa(coding);
}
model {
  Θ ~ LogNormal(meanlog=3.0, sdlog=1.0);
  ψ ~ Coalescent(theta=Θ, taxa=taxa);
  π ~ Dirichlet(conc=[2.0,2.0,2.0,2.0]);
  coding ~ PhyloCTMC(tree=ψ, L=L1, Q=f81(freq=π));
  noncoding ~ PhyloCTMC(tree=ψ, L=L2, Q=f81(freq=π));
}

**Comment by walterxie** [comment]
add `partition` function

**Comment by alexeid** [comment]
Nice start. But I think we should remember that this language must be as succinct as possible. There is some redundancy in that proposed code. I would rather something like this:

```
data {
   coding = nexus(file="primates.nex", charset="coding");
   noncoding = nexus(file="primates.nex", charset="noncoding");
  L1 = nchar(coding);
  L2 = nchar(noncoding);
  taxa = taxa(coding);
}

model {
  Θ ~ LogNormal(meanlog=3.0, sdlog=1.0);
  ψ ~ Coalescent(theta=Θ, taxa=taxa);
  π ~ Dirichlet(conc=[2.0,2.0,2.0,2.0]);
  coding ~ PhyloCTMC(tree=ψ, L=L1, Q=f81(freq=π));
  noncoding ~ PhyloCTMC(tree=ψ, L=L2, Q=f81(freq=π));
}
```

**Comment by walterxie** [comment]
In first nexus function call, save the alignment in a static Map<String, Alignment>.
In the nexus second function call, see if it already has an Alignment in the static map, if not read the file again.

**Comment by walterxie** [comment]
The example file `primate.nex` has extra partitions in Nexus, so I setup a warning message to report this situation:

Warning: there is extra partition(s) defined in Nexus, where the total nchar in each part 1591 != 898 the length of full alignment !
Partitions (ntaxa by nchar) : {1stpos=12 by 231, 2ndpos=12 by 231, 3rdpos=12 by 231, coding=12 by 693, noncoding=12 by 205}

**Comment by walterxie** [comment]
The script is working.
