### ISSUE TITLE
LPhyBEAST value's parsing error for numbers

### ISSUE THREAD

**Issue by walterxie** [alexeid/linguaPhylo#69]
`Θ ~ LogNormal(meanlog=3, sdlog=1);` will have value parsing error in LPhyBEAST, where 3 and 1 will parse to IntergerParameter instead of RealParameter in BEAST.

In addition, some functions e.g. `LogNormal` should guarantee parameters are doubles in the constructor: 

`M = doubleValue(M), S= doubleValue(S)`

So the type can use Double:

```
private Value<Number> M;
private Value<Number> S;
```

**Comment by alexeid** [comment]
This is not a bug in LPHY. LogNormal is designed carefully to handle both integer and double input. This is an error in LPHYBEAST.
